# These are supported funding model platforms

github: #tijuks
patreon: #tijuks
open_collective: #tijuks
ko_fi: # tijuks
tidelift: #tijuks
community_bridge: #tijuks
liberapay: #tijuks
issuehunt: # tijuks
lfx_crowdfunding: # tijuks
polar: # tijuks 
buy_me_a_coffee: # Replace with a single Buy Me a Coffee sername
thanks_dev:#tijuks
custo: #https://github.com/Sponsor/tijuks
