on: push
jobs:

  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [linux, macOS, windows]
    actions:
    - name: npm install
      run: npm install

    - name: Lint
      run: npm run format-check

    - name: npm test
      run: npm test
