trigger:
- master
- features/*

jobs:
- job: Tests
  displayName: Run tests
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      windows:
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10"

  - script: npm install

  - script: npm test

- job: Lint
  displayName: Linting
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10"

  - script: npm install

  - script: npm run format-check