sources:
  npm: true

allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
                - name: Setup Node.js environment
                uses: actions/setup-node@v4.1.0
            
