sources:
  npm: true

allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
    # This is under an MIT license
    - color-convert
    # This is under an MIT license
    - colors
    # This is under a BSD-3-Clause license
    - duplexer3