name: Hello world work flow

on:
  push:
    branches:
      -suyash-test-1
  pull_request:
    branches:
      -suyash-test-1
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello world"
        shell: bash
